### ISSUE TITLE
No module named 'rl_bakery' found

### ISSUE THREAD

**Issue by rachitm12** [zynga/rl-bakery#10]
I tried updating the OS path and i followed the steps as mentioned in your file but I am still unable to run any of the examples. Is there any resource i can check?
Thanks!

**Comment by jpg2174** [comment]
> I tried updating the OS path and i followed the steps as mentioned in your file but I am still unable to run any of the examples. Is there any resource i can check?
> Thanks!

same issue on my end :(

**Comment by patrick-halina** [comment]
Hey, sorry for the issues. I just checked out the repo and it worked for me. I suspect the issue is the definition of 'root directory'.  You should be in the top level of the repo (eg. your present working directory should be rl-bakery, not rl-bakery/rl-bakery.) You should be able to run this command to get an example application running: `python -m rl_bakery.example.cartpole`. I updated the Readme instructions to be clearer.  Let me know if you still have issues!

**Comment by rachitm12** [comment]
> Hey, sorry for the issues. I just checked out the repo and it worked for me. I suspect the issue is the definition of 'root directory'. You should be in the top level of the repo (eg. your present working directory should be rl-bakery, not rl-bakery/rl-bakery.) You should be able to run this command to get an example application running: `python -m rl_bakery.example.cartpole`. I updated the Readme instructions to be clearer. Let me know if you still have issues!
